"""Add cascade delete for executions

Revision ID: 36c3fcd1a555
Revises: 47f199631a1b
Create Date: 2026-03-06 14:06:08.784040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c3fcd1a555'
down_revision: Union[str, Sequence[str], None] = '47f199631a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 级联删除设置在模型中定义，不需要在迁移文件中体现
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
