"""modify_execution_log_node_id

Revision ID: 3eb21563128d
Revises: 36c3fcd1a555
Create Date: 2026-03-08 17:40:00.107141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb21563128d'
down_revision: Union[str, Sequence[str], None] = '36c3fcd1a555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_logs', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'") if hasattr(sa, 'text') else None)
    op.drop_constraint('execution_logs_node_id_fkey', 'execution_logs', type_='foreignkey')
    op.create_foreign_key(None, 'execution_logs', 'nodes', ['node_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'execution_logs', type_='foreignkey')
    op.create_foreign_key('execution_logs_node_id_fkey', 'execution_logs', 'nodes', ['node_id'], ['id'])
    op.alter_column('execution_logs', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'") if hasattr(sa, 'text') else None)
    # ### end Alembic commands ###
