"""Update file and flow models for file system integration

Revision ID: 47f199631a1b
Revises: 6fd6dbd5bb69
Create Date: 2026-03-06 13:56:32.452054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f199631a1b'
down_revision: Union[str, Sequence[str], None] = '6fd6dbd5bb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加flow_id列，允许NULL
    op.add_column('files', sa.Column('flow_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.create_index(op.f('ix_files_flow_id'), 'files', ['flow_id'], unique=False)
    op.create_index(op.f('ix_files_parent_id'), 'files', ['parent_id'], unique=False)
    op.drop_constraint(op.f('files_parent_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_user_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'files', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'files', 'flows', ['flow_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'path')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_user_id_fkey'), 'files', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('files_parent_id_fkey'), 'files', 'files', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_files_parent_id'), table_name='files')
    op.drop_index(op.f('ix_files_flow_id'), table_name='files')
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.drop_column('files', 'flow_id')
    # ### end Alembic commands ###
